local api = vim.api
local studio = require("next_studio")
local layout = require("next_studio.layout")
local controls = require("next_studio.controls")
local store = require("next_studio.store")
local sandbox = assert(vim.env.NEXT_STUDIO_TEST_ROOT)
local root = store.canonical(sandbox .. "/projects/ALPHA")
local checks = 0
local function check(value, message) assert(value, message); checks = checks + 1 end
local function normal_wins()
  return vim.tbl_filter(function(win) return api.nvim_win_get_config(win).relative == "" end, api.nvim_tabpage_list_wins(0))
end
local function role(kind)
  for _, win in ipairs(normal_wins()) do if layout.kind(win) == kind then return win end end
end
local function shape(node)
  if not node.children then return node.kind .. (node.title and ":" .. node.title or "") end
  local parts = {}; for _, c in ipairs(node.children) do parts[#parts + 1] = shape(c) end
  return node.kind .. "(" .. table.concat(parts, ",") .. ")"
end

check(studio.open(root), "Plain Neovim opens a Studio project")
check(_G.Snacks == nil and _G.LazyVim == nil, "Core does not depend on a distribution or UI plugin")
check(#normal_wins() == (vim.env.NEXT_STUDIO_PHASE == "restart" and 4 or 3), "Workspace has its expected pane count")
check(vim.fn.exists(":StudioFiles") == 0 and vim.fn.exists(":StudioFilesToggle") == 0 and studio.keys.f == nil and studio.keys.F == nil, "Studio leaves file browsing to existing Neovim tools")

if vim.env.NEXT_STUDIO_PHASE == "restart" then
  check(role("notes") ~= nil, "Notes role restores in a fresh Neovim")
  local buf = api.nvim_win_get_buf(role("notes"))
  check(table.concat(api.nvim_buf_get_lines(buf, 0, -1, false), "\n"):find("SYNTHETIC_NOTE", 1, true) ~= nil, "Private notes persist across restarts")
  check(vim.w[role("terminal")].next_studio_title == "Build log", "Custom terminal title survives restart")
  check(require("next_studio.tasks").projects[root] == nil, "Stored layouts never restart task commands")
else
  local editor, terminal = role("editor"), role("terminal")
  api.nvim_set_current_win(editor)
  vim.cmd.edit(vim.fn.fnameescape(root .. "/example.txt"))
  local original = api.nvim_get_current_buf()
  api.nvim_buf_set_lines(original, 0, -1, false, { "SYNTHETIC_UNSAVED", "second line" })
  api.nvim_win_set_cursor(editor, { 2, 3 })
  local job = vim.b[api.nvim_win_get_buf(terminal)].terminal_job_id
  local dimensions = vim.fn.winrestcmd()
  studio.zoom()
  check(controls.zoomed and api.nvim_get_current_buf() == original and #normal_wins() == 3, "Zoom uses the same buffer without destroying splits")
  api.nvim_win_set_cursor(0, { 1, 4 })
  studio.zoom()
  check(api.nvim_get_current_win() == editor and vim.fn.winrestcmd() == dimensions, "Zoom returns to the same window and exact sizes")
  check(api.nvim_win_get_cursor(editor)[2] == 4, "Cursor edits in zoom return to the source")

  studio.rename("API %f")
  check(vim.w.next_studio_title == "API %f" and vim.wo.winbar == "", "Pane names remain metadata without consuming a title row")
  local agent = role("agent")
  studio.exchange(agent)
  check(api.nvim_win_get_buf(agent) == original and vim.w[agent].next_studio_title == "API %f", "Swap moves buffers and titles together")
  check(vim.fn.winrestcmd() == dimensions, "Swap does not resize windows")
  studio.undo()
  check(api.nvim_win_get_buf(role("editor")) == original, "Layout undo restores the moved editor")
  studio.undo(true)
  check(api.nvim_get_current_buf() == original, "Redo restores the swapped focused pane")
  studio.undo()
  check(api.nvim_buf_is_valid(original) and vim.bo[original].modified, "Layout history preserves unsaved text")
  check(vim.fn.jobwait({ job }, 0)[1] == -1, "Layout history preserves the existing shell process")

  api.nvim_set_current_win(role("editor"))
  local before = shape(layout.capture(root))
  studio.split("vertical")
  local scratch = api.nvim_get_current_buf()
  api.nvim_buf_set_lines(scratch, 0, -1, false, { "SYNTHETIC_SCRATCH" })
  studio.undo()
  check(shape(layout.capture(root)) == before and api.nvim_buf_is_valid(scratch), "Undo split retains the newly typed scratch buffer")
  studio.undo(true)
  check(api.nvim_get_current_buf() == scratch, "Redo split recovers the same scratch buffer")
  studio.pane("agent")
  studio.undo()
  check(api.nvim_get_current_buf() == scratch, "Undo type change restores the same scratch buffer")
  studio.close()
  studio.undo()
  check(api.nvim_get_current_buf() == scratch, "Undo close reopens the retained buffer")
  studio.undo(true)

  api.nvim_set_current_win(role("editor"))
  local editor_map = function() end
  vim.keymap.set("n", "j", editor_map, { buffer = true })
  local widths = vim.fn.winrestcmd()
  studio.resize()
  vim.fn.maparg("l", "n", false, true).callback()
  check(vim.fn.winrestcmd() ~= widths, "Resize changes the chosen boundary")
  controls.finish_resize(true)
  check(vim.fn.winrestcmd() == widths, "Escape resize restores exact prior dimensions")
  check(vim.fn.maparg("j", "n", false, true).callback == editor_map, "Resize restores existing buffer-local keymaps")
  studio.resize()
  vim.fn.maparg("l", "n", false, true).callback()
  controls.finish_resize()
  check(not controls.resizing and #require("next_studio.history").tabs[api.nvim_get_current_tabpage()].undo > 0, "Committed resize joins layout history")
  studio.undo()

  studio.notes()
  check(layout.kind(0) == "notes", "Project Notes is a first-class pane type")
  local note = api.nvim_get_current_buf()
  api.nvim_buf_set_lines(note, 0, -1, false, { "# Project Notes", "", "- [ ] SYNTHETIC_NOTE" })
  api.nvim_win_set_cursor(0, { 3, 0 })
  require("next_studio.notes").check()
  check(api.nvim_get_current_line() == "- [x] SYNTHETIC_NOTE", "Notes checkboxes toggle with one action")
  check(require("next_studio.notes").save(note), "Notes save separately from layouts")
  local note_path = store.directory() .. "/notes/" .. vim.fn.sha256(root) .. ".md"
  check(vim.uv.fs_stat(note_path).mode % 512 == 384, "Notes files have private permissions")
  check(not vim.uv.fs_stat(root .. "/notes.md"), "Notes do not write into the project checkout")
  api.nvim_buf_set_lines(note, -1, -1, false, { "SYNTHETIC_LOCAL_EDIT" })
  local lock = assert(vim.uv.fs_open(note_path .. ".lock", "wx", 384))
  check(not require("next_studio.notes").save(note) and vim.bo[note].modified, "A busy Notes writer keeps this editor's changes")
  vim.uv.fs_close(lock)
  vim.uv.fs_unlink(note_path .. ".lock")
  local external = assert(vim.uv.fs_open(note_path, "a", 384))
  vim.uv.fs_write(external, "SYNTHETIC_EXTERNAL_EDIT\n", -1)
  vim.uv.fs_close(external)
  check(not require("next_studio.notes").save(note) and vim.bo[note].modified, "Concurrent Notes changes refuse overwrite and preserve the local buffer")
  -- This disposable buffer deliberately abandons its local conflict after the check.
  vim.bo[note].modified = false
  studio.pane("editor")
  studio.pane("notes")
  check(api.nvim_get_current_buf() == note, "Changing back reuses this project's notes")

  local task = require("next_studio.tasks").start(root, { name = "Synthetic task", cmd = { "/bin/sh", "-c", "printf 'SYNTHETIC_TASK_OUTPUT\n'" } })
  vim.wait(1000, function() return task.code ~= nil end)
  check(task.code == 0 and api.nvim_buf_is_valid(task.buf), "Explicit project commands retain their output")
  check(table.concat(api.nvim_buf_get_lines(task.buf, 0, -1, false), "\n"):find("SYNTHETIC_TASK_OUTPUT", 1, true), "Task output is visible in its terminal pane")
  studio.close()
  studio.undo()
  check(api.nvim_get_current_buf() == task.buf, "Undo keeps completed task output")
  studio.close()
  api.nvim_set_current_win(role("terminal"))
  studio.rename("Build log")
  check(studio.save("Portable"), "Portable layout saves")
  local data = store.load(root)
  local encoded = vim.json.encode(data)
  check(not encoded:find("SYNTHETIC_UNSAVED", 1, true) and not encoded:find("SYNTHETIC_NOTE", 1, true)
    and not encoded:find("SYNTHETIC_TASK_OUTPUT", 1, true) and not encoded:find("_options", 1, true), "Saved layouts exclude text, commands, output and in-memory history")
  local diagram = table.concat(require("next_studio.layout_picker").diagram(data.layouts.Portable, 80, 24), "\n")
  check(diagram:find("PROJECT NOTES", 1, true) and diagram:find("Build log", 1, true), "Layout preview renders pane roles and custom names")
  studio.layouts()
  check(require("next_studio.layout_picker").active ~= nil, "Layout preview opens without Snacks")
  local picker = require("next_studio.layout_picker").active
  api.nvim_win_close(picker.win, true)
  check(require("next_studio.layout_picker").active == nil, "Closing a layout preview cleans up its active state")
end
print("PASS standalone " .. (vim.env.NEXT_STUDIO_PHASE or "first") .. ": " .. checks .. " checks")
vim.cmd("qa!")
